// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACzK0BTdexL_25vaAKNEroOZ3HIMm1pLQ',
    appId: '1:503281284694:web:61e3a73adf7f6795196df7',
    messagingSenderId: '503281284694',
    projectId: 'news-letter-f03c9',
    authDomain: 'news-letter-f03c9.firebaseapp.com',
    storageBucket: 'news-letter-f03c9.firebasestorage.app',
    measurementId: 'G-MJZH5QCYMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCio4RwMTg4YgmXwTrTz79K1Ug9w71wJAU',
    appId: '1:503281284694:android:ad6b0dc9a74cc5f4196df7',
    messagingSenderId: '503281284694',
    projectId: 'news-letter-f03c9',
    storageBucket: 'news-letter-f03c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRgp8uIO5kPSs1Sqf4fe8PSXcfRPwJ8I',
    appId: '1:503281284694:ios:850e8793655cf843196df7',
    messagingSenderId: '503281284694',
    projectId: 'news-letter-f03c9',
    storageBucket: 'news-letter-f03c9.firebasestorage.app',
    iosBundleId: 'com.example.newsLetter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRgp8uIO5kPSs1Sqf4fe8PSXcfRPwJ8I',
    appId: '1:503281284694:ios:850e8793655cf843196df7',
    messagingSenderId: '503281284694',
    projectId: 'news-letter-f03c9',
    storageBucket: 'news-letter-f03c9.firebasestorage.app',
    iosBundleId: 'com.example.newsLetter',
  );

}